blog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from blog.views import (
    BlogCreateView,
    BlogListView,
    BlogDetailView,
    BlogUpdateView,
    BlogDeleteView,
)

from blog.apps import BlogConfig

app_name = BlogConfig.name

urlpatterns = [
    path("create/", cache_page(60)(BlogCreateView.as_view()), name="create"),
    path("", BlogListView.as_view(), name="blog_list"),
    path("view/<int:pk>/", BlogDetailView.as_view(), name="view"),
    path("edit/<int:pk>/", BlogUpdateView.as_view(), name="edit"),
    path("delete/<int:pk>/", BlogDeleteView.as_view(), name="delete"),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from config import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('blog/', include('blog.urls')),
    path('users/', include('users.urls', namespace='users')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from main.apps import MainConfig
from main.views import (
    Index,
    MailingListView,
    MailingCreateView,
    MailingDeleteView,
    MailingDetailView,
    MailingUpdateView,
    MailingUpdateModeratorView,
    MessageListView,
    MessageCreateView,
    MessageUpdateView,
    MessageDeleteView,
    MessageDetailView,
    ClientListView,
    ClientCreateView,
    ClientUpdateView,
)

app_name = MainConfig.name

urlpatterns = [
    path("", cache_page(60)(Index.as_view()), name="index"),
    path("mailing/", MailingListView.as_view(), name="mailing_list"),
    path("mailing/create/", MailingCreateView.as_view(), name="mailing_create"),
    path("mailing/detail/<int:pk>/", MailingDetailView.as_view(), name="mailing_detail"),
    path("mailing/update/<int:pk>/", MailingUpdateView.as_view(), name="mailing_update"),
    path("mailing_mod_edit/<int:pk>/", MailingUpdateModeratorView.as_view(), name="mailing_mod_edit"),
    path("mailing_delete/<int:pk>/", MailingDeleteView.as_view(), name="mailing_delete"),

    path("message_list/", MessageListView.as_view(), name="message_list"),
    path("message_add/", MessageCreateView.as_view(), name="message_add"),
    path("message_edit/<int:pk>/", MessageUpdateView.as_view(), name="message_edit"),
    path("message_view/<int:pk>/", MessageDetailView.as_view(), name="message_view"),
    path("message_delete/<int:pk>/", MessageDeleteView.as_view(), name="message_delete"),

    path("clients/", ClientListView.as_view(), name="client_list"),
    path("client_add/", ClientCreateView.as_view(), name="client_add"),
    path("client_edit/<int:pk>", ClientUpdateView.as_view(), name="client_edit")
]

users/urls.py
from django.urls import path
from django.views.generic import TemplateView

from users.apps import UsersConfig
from users.views import (
    LogoutView,
    UserLoginView,
    RegisterView,
    verification,
    UserUpdateView,
    get_users_list,
)

app_name = UsersConfig.name

urlpatterns = [
    path("", UserLoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("register/", RegisterView.as_view(template_name="users/register.html"), name="register"),
    path("verify_message/", TemplateView.as_view(template_name="users/verify_message.html"), name="verify_message"),
    path("email/verify/<str:verify_code>", verification, name="verify"),
    path("success_verify/", TemplateView.as_view(template_name="users/success_verify.html"), name="success_verify"),
    path("invalid_verify/", TemplateView.as_view(template_name="users/invalid_verify.html"), name="invalid_verify"),
    path("users_list/", get_users_list, name="list_view"),
    path("edit/<int:pk>", UserUpdateView.as_view(), name="edit"),
]

main/models.py
from django.utils import timezone
from django.db import models

from users.models import User

NULLABLE = {
    "blank": True,
    "null": True,
}


class Client(models.Model):
    """Клиент - тот, кто получает рассылки"""

    email = models.EmailField(verbose_name="контактный email")
    name = models.CharField(max_length=255, verbose_name="Ф. И. О.")
    comment = models.TextField(**NULLABLE, verbose_name="комментарий")
    user = models.ForeignKey(
        User, on_delete=models.CASCADE, verbose_name="пользователь", null=True
    )

    class Meta:
        verbose_name = "клиент"
        verbose_name_plural = "клиенты"

    def __str__(self):
        return f"{self.email}"


class Message(models.Model):
    """ Сообщение клиенту """

    subject = models.CharField(max_length=150, verbose_name="тема")
    body = models.TextField(verbose_name="тело")
    user = models.ForeignKey(
        User, on_delete=models.CASCADE,
        null=True, verbose_name="Пользователь сообщения"
    )

    def __str__(self):
        return f"{self.subject} {self.body}"

    class Meta:
        verbose_name = "сообщение"
        verbose_name_plural = "сообщение"


class Mailing(models.Model):
    """ Рассылка клиенту """

    CHOICES_INTERVAL = [
        ("day", "раз в день"),
        ("week", "раз в неделю"),
        ("month", "раз в месяц"),
    ]

    STATUS_CHOICES = [
        ("completed", "Завершена"),
        ("created", "Создана"),
        ("launched", "Запущена"),
    ]

    title = models.CharField(max_length=255, verbose_name="заголовок рассылки")
    client = models.ManyToManyField(Client, verbose_name="клиенты")
    message = models.ForeignKey(
        Message, on_delete=models.CASCADE, null=True, verbose_name="сообщение"
    )
    start_date = models.DateTimeField(default=timezone.now,
                                      verbose_name="дата начала")
    next_date = models.DateTimeField(
        default=timezone.now, verbose_name="следующая дата"
    )
    end_date = models.DateTimeField(default=timezone.now,
                                    verbose_name="конечная дата")
    periodicity = models.CharField(
        default="разовая",
        max_length=64,
        choices=CHOICES_INTERVAL,
        verbose_name="периодичность",
    )
    status = models.CharField(
        max_length=64,
        choices=STATUS_CHOICES,
        verbose_name="статус рассылки",
        **NULLABLE,
    )
    is_active = models.BooleanField(default=True, verbose_name="актуальная")
    user = models.ForeignKey(
        User, on_delete=models.CASCADE,
        verbose_name="пользователь", **NULLABLE
    )

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "Рассылка"
        verbose_name_plural = "Рассылки"
        ordering = ("start_date",)
        permissions = [("set_is_activated",
                        "Может менять активность рассылки")]


class Logs(models.Model):
    """ Логирование рассылок """

    mailing = models.ForeignKey(Mailing,
                                on_delete=models.CASCADE,
                                verbose_name="рассылка", **NULLABLE)
    last_mailing_time = models.DateTimeField(auto_now=True,
                                             verbose_name="время "
                                                          "последней рассылки")
    status = models.CharField(max_length=64,
                              verbose_name="статус попытки рассылки",
                              null=True)
    response = models.CharField(max_length=256,
                                verbose_name="ответ сервера", **NULLABLE)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.last_mailing_time = None

    def __str__(self):
        return f'{self.mailing}, {self.status}'

    class Meta:
        verbose_name = "лог"
        verbose_name_plural = "логи"

main/forms.py
from django import forms
from django.forms import DateTimeInput, CheckboxInput

from main.models import Mailing, Message, Client


class StylingFormMixin(forms.Form):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for field_name, field in self.fields.items():
            if field_name == "is_active":
                field.widget.attrs["class"] = "form-check-input"
            else:
                field.widget.attrs["class"] = "form-control"


class MailingForm(StylingFormMixin, forms.ModelForm):

    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop("request")
        user = self.request.user
        super().__init__(*args, **kwargs)
        self.fields["client"].queryset = Client.objects.filter(user=user)
        self.fields["message"].queryset = Message.objects.filter(user=user)

    class Meta:
        model = Mailing
        exclude = ("next_date", "user", "is_active")

        widgets = {
            "start_date": DateTimeInput(
                attrs={"placeholder": "ДД.ММ.ГГГГ ЧЧ:ММ:СС",
                       "type": "datetime-local"}
            ),
            "end_date": DateTimeInput(
                attrs={"placeholder": "ДД.ММ.ГГГГ ЧЧ: ММ:СС",
                       "type": "datetime-local"}
            ),
            "is_active": CheckboxInput(attrs={}),
        }


class MailingModerForm(StylingFormMixin, forms.ModelForm):
    class Meta:
        model = Mailing
        fields = ("is_active",)


class MessageForm(StylingFormMixin, forms.ModelForm):
    class Meta:
        model = Message
        exclude = ("user",)


class ClientForm(StylingFormMixin, forms.ModelForm):
    class Meta:
        model = Client
        exclude = ("user",)

main/views.py
import random
from django.contrib.auth.mixins import (
    LoginRequiredMixin,
    UserPassesTestMixin,
    PermissionRequiredMixin,
)
from django.urls import reverse_lazy, reverse
from django.views.generic import (
    CreateView,
    ListView,
    DetailView,
    UpdateView,
    DeleteView,
)
from blog.models import Blog
from main.forms import MailingForm, MessageForm, ClientForm, MailingModerForm
from main.models import Message, Mailing, Client, Logs
from main.services import get_cache_for_mailings, get_cache_for_active_mailings


class Index(ListView):
    model = Mailing
    template_name = "main/index.html"

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data["mailings_count"] = get_cache_for_mailings()
        context_data["active_mailings_count"] = get_cache_for_active_mailings()
        blog_list = list(Blog.objects.all())
        random.shuffle(blog_list)
        context_data["blog_list"] = blog_list[:3]
        context_data["clients_count"] = len(Client.objects.all())
        return context_data


class MailingCreateView(LoginRequiredMixin, CreateView):
    model = Mailing
    form_class = MailingForm
    success_url = reverse_lazy("main:mailing_list")
    extra_context = {"title": "Создание рассылки"}

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs.update({"request": self.request})
        return kwargs

    def form_valid(self, form, *args, **kwargs):
        if form.is_valid():
            new_mailing = form.save(commit=False)
            new_mailing.user = self.request.user
            new_mailing.save()
        return super().form_valid(form)


class MailingUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Mailing
    form_class = MailingForm
    success_url = reverse_lazy("main:mailing_list")

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs.update({"request": self.request})
        return kwargs

    def test_func(self):
        if self.request.user.is_staff:
            return True
        return (self.request.user == Mailing.objects.get(
            pk=self.kwargs["pk"]).user)


class MailingUpdateModeratorView(
    LoginRequiredMixin, PermissionRequiredMixin, UpdateView
):
    model = Mailing
    form_class = MailingModerForm
    success_url = reverse_lazy("main:mailing_list")
    permission_required = "main.set_is_activated"


class MailingListView(LoginRequiredMixin, ListView):
    model = Mailing
    extra_context = {"title": "Список рассылок"}


class MailingDetailView(DetailView):
    model = Mailing

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['clients'] = list(self.object.client.all())
        context_data['logs'] = list(Logs.objects.all())
        return context_data


class MailingDeleteView(DeleteView):
    model = Mailing
    success_url = reverse_lazy("main:mailing_list")


class MessageCreateView(LoginRequiredMixin, CreateView):
    model = Message
    form_class = MessageForm
    success_url = reverse_lazy("main:message_list")
    extra_context = {"title": "Создание сообщения"}

    def form_valid(self, form):
        new_message = form.save()
        new_message.user = self.request.user
        new_message.save()
        return super().form_valid(form)


class MessageUpdateView(LoginRequiredMixin, UpdateView):
    model = Message
    form_class = MessageForm

    def get_success_url(self):
        return reverse("main:message_view", args=[self.kwargs.get("pk")])


class MessageDetailView(LoginRequiredMixin, DetailView):
    model = Message


class MessageListView(LoginRequiredMixin, ListView):
    model = Message
    extra_context = {"title": "Список сообщений"}

    def get_queryset(self, *args, **kwargs):
        queryset = super().get_queryset(*args, **kwargs)
        queryset = Message.objects.filter(user=self.request.user)
        return queryset


class MessageDeleteView(LoginRequiredMixin, DeleteView):
    model = Message
    success_url = reverse_lazy("main:message_list")


class ClientListView(LoginRequiredMixin, ListView):
    model = Client
    extra_context = {"title": "Список клиентов"}

    def get_queryset(self, *args, **kwargs):
        queryset = super().get_queryset(*args, **kwargs)
        queryset = Client.objects.filter(user=self.request.user)
        return queryset


class ClientCreateView(LoginRequiredMixin, CreateView):
    model = Client
    form_class = ClientForm
    success_url = reverse_lazy("main:client_list")
    extra_context = {"title": "Добавить клиента"}

    def form_valid(self, form):
        new_client = form.save()
        new_client.user = self.request.user
        new_client.save()
        return super().form_valid(form)


class ClientUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Client
    form_class = ClientForm
    success_url = reverse_lazy("main:client_list")

    def test_func(self):
        return self.request.user == Client.objects.get(
            pk=self.kwargs["pk"]).user

main/templates/main/base.html
{% load static %}

<!doctype html>
<html lang="en" data-bs-theme="auto">
<head>
    <script src="{% static 'js/color-modes.js' %}"></script>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Сервис рассылки</title>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@docsearch/css@3">
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" type="text/css">

    <meta name="theme-color" content="#712cf9">

    <style>
        .bd-placeholder-img {
          font-size: 1.125rem;
          text-anchor: middle;
          -webkit-user-select: none;
          -moz-user-select: none;
          user-select: none;
        }

        @media (min-width: 768px) {
          .bd-placeholder-img-lg {
            font-size: 3.5rem;
          }
        }

        .b-example-divider {
          width: 100%;
          height: 3rem;
          background-color: rgba(0, 0, 0, .1);
          border: solid rgba(0, 0, 0, .15);
          border-width: 1px 0;
          box-shadow: inset 0 .5em 1.5em rgba(0, 0, 0, .1), inset 0 .125em .5em rgba(0, 0, 0, .15);
        }

        .b-example-vr {
          flex-shrink: 0;
          width: 1.5rem;
          height: 100vh;
        }

        .bi {
          vertical-align: -.125em;
          fill: currentColor;
        }

        .nav-scroller {
          position: relative;
          z-index: 2;
          height: 2.75rem;
          overflow-y: hidden;
        }

        .nav-scroller .nav {
          display: flex;
          flex-wrap: nowrap;
          padding-bottom: 1rem;
          margin-top: -1px;
          overflow-x: auto;
          text-align: center;
          white-space: nowrap;
          -webkit-overflow-scrolling: touch;
        }

        .btn-bd-primary {
          --bd-violet-bg: #712cf9;
          --bd-violet-rgb: 112.520718, 44.062154, 249.437846;

          --bs-btn-font-weight: 600;
          --bs-btn-color: var(--bs-white);
          --bs-btn-bg: var(--bd-violet-bg);
          --bs-btn-border-color: var(--bd-violet-bg);
          --bs-btn-hover-color: var(--bs-white);
          --bs-btn-hover-bg: #6528e0;
          --bs-btn-hover-border-color: #6528e0;
          --bs-btn-focus-shadow-rgb: var(--bd-violet-rgb);
          --bs-btn-active-color: var(--bs-btn-hover-color);
          --bs-btn-active-bg: #5a23c8;
          --bs-btn-active-border-color: #5a23c8;
        }

        .bd-mode-toggle {
          z-index: 1500;
        }

        .bd-mode-toggle .dropdown-menu .active .bi {
          display: block !important;
        }
    </style>


    <!-- Custom styles for this template -->
    <link href="https://fonts.googleapis.com/css?family=Playfair&#43;Display:700,900&amp;display=swap" rel="stylesheet">
    <!-- Custom styles for this template -->
    <link href="{% static 'css/blog.css' %}" rel="stylesheet">
</head>
<body>

<!--Header and navigation-->
<div class="container">
    {% include 'main/header.html' %}
    {% include 'main/navigation.html' %}
</div>


<main class="container">
    {% block content %}
    {% endblock %}
</main>

{% include 'main/footer.html' %}


<script src="{% static 'js/bootstrap.bundle.min.js' %}"
        crossorigin="anonymous"></script>


</body>
</html>

main/templates/main/client_form.html
{% extends 'main/base.html' %}

{% block content %}
<div class="header mx-auto text-center">
    <h5 class="display-4">{{ title }}</h5>
</div>
<div class="col-12">
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form.as_p }}
                        {% if object %}
                            <button type="submit" class="btn btn-primary">Сохранить</button>
                        {% else %}
                            <button type="submit" class="btn btn-primary">Создать</button>
                        {% endif %}
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

main/templates/main/client_list.html
{% extends 'main/base.html' %}
{% block content %}
<div class="header mx-auto text-center mb-4">
    <h5 class="display-4">{{ title }}</h5>
</div>
<div class="col-12 mb-5">
    <a class="btn btn-outline-primary"
       href="{% url 'main:client_add' %}">Добавить клиента</a>
</div>
<div class="col-12">
    <div class="row">
        {% for object in object_list %}
            <div class="col-12 mb-4">
                <div class="card">
                    <div class="card-body">
                        <p>{{ object.email }}</p>
                        {% if object.comment %}
                            <p>{{ object.comment }}</p>
                        {% endif %}

                        <a href="{% url 'main:client_edit' object.pk %}"
                           class="btn btn-sm btn-outline-secondary">Редактировать</a>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

main/templates/main/footer.html
<footer class="py-5 text-center text-body-secondary bg-body-tertiary">
    <div class="col-12 col-md">
            Мир рассылок с нами
            <small class="d-block mb-3 text-muted">&copy; 2024</small>
        </div>
    <p class="mb-0">
        <a href="#">Наверх</a>
    </p>
</footer>

main/templates/main/header.html
<!--<div class="container">-->
<header class="border-bottom lh-1 py-3">
    <div class="row flex-nowrap justify-content-between align-items-center">
        <div class="col-4 pt-1">
            <a class="p-2 btn btn-outline-secondary" href="{% url 'users:register' %}">Регистрация</a>
        </div>
        <div class="col-4 text-center">
            <a class="blog-header-logo text-body-emphasis text-decoration-none" href="#">Сервис рассылок</a>
        </div>


        <div class="col-4 d-flex justify-content-end align-items-center">
            {% if user.is_authenticated %}
            <a class="btn btn-outline-secondary" href="{% url 'users:logout' %}">Выйти</a>
            {% else %}
            <a class="btn btn-outline-secondary" href="{% url 'users:login' %}">Войти</a>
            {% endif %}


        </div>
    </div>
</header>

main/templates/main/mailing_confirm_delete.html
{% extends 'main/base.html' %}
{% block content %}
 <div class="col-12">
        <div class="row">
            <div class="col-6">
                <div class="card">
                    <div class="card-body">
                        <form method="post">
                            {% csrf_token %}
                            <p>Хотите удалить сообщение "{{ object.title }}"?</p>
                            <button type="submit" class="btn btn-primary">Подтвердить</button>
                            <a href="{% url 'main:mailing_list' %}" class="btn btn-warning">Отмена</a>

                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

main/templates/main/mailing_detail.html
{% extends 'main/base.html' %}
{% block content %}


<h2 class="mb-4">Карточка рассылки</h2>


<div class="col-12 mb-4">
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-body">
                    <table class="table">
                        <tr>
                            <td>Заголовок:</td>
                            <td>{{ object.title }}</td>
                        </tr>

                        <tr>
                            <td>Клиенты:</td>
                            <td>

                                {% for client in object.client.all %}
                                {{ client}}
                                {% endfor %}
                            </td>
                        </tr>

                        <tr>
                            <td>Сообщение:</td>
                            <td>{{ object.message.subject }}</td>
                        </tr>

                        <tr>
                            <td>Старт рассылки:</td>
                            <td>{{ object.start_date }}</td>
                        </tr>

                        <tr>
                            <td>Завершение рассылки:</td>
                            <td>{{ object.end_date }}</td>
                        </tr>

                        <tr>
                            <td>Периодичность:</td>
                            <td>{{ object.get_periodicity_display }}</td>
                        </tr>

                        <tr>
                            <td>Текущий статус:</td>
                            <td>{{ object.get_status_display }}</td>
                        </tr>

                        <tr>
                            <td>Активная:</td>
                            {% if object.is_active %}
                            <td>да</td>
                            {% else %}
                            <td>нет</td>
                            {% endif %}
                        </tr>

                        <tr>
                            <td>Автор:</td>
                            <td>{{ object.user }}</td>
                        </tr>


                    </table>

                </div>

                <div class="d-flex justify-content-between align-items-center">
                    <div class="btn-group m-4">
                        {% if user.is_superuser or user == object.user %}
                        <a href="{% url 'main:mailing_update' object.pk %}" type="button"
                           class="btn btn-sm btn-outline-primary">Редактировать</a>
                        <a href="{% url 'main:mailing_delete' object.pk %}" type="button"
                           class="btn btn-sm btn-outline-danger">Удалить</a>
                        {% endif %}


                        {% if perms.main.set_is_activated %}
                        <a href="{% url 'main:mailing_mod_edit' object.pk %}" type="button"
                           class="btn btn-sm btn-outline-primary">Модерация</a>
                        {% endif %}


                    </div>
                </div>
            </div>
        </div>
    </div>


    <h2 class="mb-4">Логи рассылки</h2>

    <div class="col-12">
        <div class="card">

            <div class="card-body">
                {% for log in logs %}
                {% if log.mailing_id == object.id %}

                <p> - {{ log.mailing  }},
                    {{ log.response }},
                    {{ log.status }}</p>
                {% endif %}
                {% endfor %}
            </div>
        </div>
    </div>


    {% endblock %}

main/templates/main/mailing_list.html
{% extends 'main/base.html' %}


{% block content %}

<a href="{% url 'main:mailing_create' %}" type="button" class="btn btn-dark mb-4">
    Создать рассылку
</a>


{% for object in object_list %}
{% if object.user == user or user.is_staff %}
<div class="card mb-4">
    <div class="card-header">
        Рассылка "<b>{{ object.title }}</b>"
    </div>
    <div class="card-body">

        <ul>
            <li>Даты: <b>{{ object.start_date }}</b> по <b>{{ object.end_date }}</b></li>
            <li>Периодичность: <b>{{ object.get_periodicity_display }}</b></li>
            {% if object.is_active %}
            <li>Статус: <b>действующая</b></li>
            {% else %}
            <li>Статус: <b>отменена</b></li>
            {% endif %}
            <li>Пользователь: <b>{{ object.user }}</b></li>
        </ul>


        <a href="{% url 'main:mailing_detail' object.pk %}" class="btn btn-dark">Поодробнее</a>
    </div>
</div>
{% endif %}

{% endfor %}

{% endblock %}

main/templates/main/message_detail.html
{% extends 'main/base.html' %}
{% block content %}
<div class="col-12">
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">{{ object.subject }}</h4>
                </div>
                <div class="card-body">
                    <p>{{ object.body }}</p>
                    {% if user == object.user %}
                    <div class="d-flex justify-content-between align-items-center">
                        <div class="btn-group">
                            <a href="{% url 'main:message_edit' object.pk %}" type="button"
                               class="btn btn-sm btn-outline-secondary">Редактировать</a>
                            <a href="{% url 'main:message_delete' object.pk %}" type="button"
                               class="btn btn-sm btn-outline-danger">Удалить</a>
                        </div>
                    </div>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

main/templates/main/message_list.html
{% extends 'main/base.html' %}
{% block content %}
<div class="header mx-auto text-center">
    <h5 class="display-4">{{ title }}</h5>
</div>
<div class="col-12 mb-5">
    <a class="btn btn-outline-primary" href="{% url 'main:message_add' %}">Создать сообщение для рассылки</a>
</div>
<div class="col-12">
    <div class="row">
        {% for object in object_list %}
        <div class="col-12 mb-4">
            <div class="card">
                <div class="card-header">
                    <h3 class="my-0 font-weight-normal">{{ object.subject }}</h3>
                </div>
                <div class="card-body">
                    <p>{{ object.body }}</p>
                    <a href="{% url 'main:message_view' object.pk %}"
                       class="btn btn-sm btn-outline-secondary">Просмотр</a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

main/templates/main/navigation.html
<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom box-shadow">
    <nav class="ms-5">
            <a class="p-2 btn btn-outline-primary" href="{% url 'main:index' %}">Главная</a>
            <a class="p-2 btn btn-outline-primary" href="{% url 'main:mailing_list' %}">Рассылки</a>
            <a class="p-2 btn btn-outline-primary" href="{% url 'main:client_list' %}">Клиенты</a>
            <a class="p-2 btn btn-outline-primary" href="{% url 'main:message_list' %}">Сообщения</a>
            <a class="p-2 btn btn-outline-primary" href="{% url 'blog:blog_list' %}">Блог</a>
            <a class="p-2 btn btn-outline-primary" href="{% url 'users:list_view' %}">Пользователи</a>
            <a class="p-2 btn btn-outline-primary" href="/admin/">Админка</a>
        </nav>
</div>